# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Standards Hub
email: team@sitron.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# font
google_font: "https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@700"
title_font_family: "Source Sans Pro"
text_font_family: "Arial"
title_color: "#1b1a41"
text_color: "#14011e"
link_color: "#00ddff"
primary_color: "#00ddff"
secondary_color: "#777777"

# navigation area
logo_height: "140px"
nav_text_color: "#ffffff"
nav_text_active_color: "#00ddff"
nav_background_color: "#14011e"
nav_transition_background_color: "#14011e"

#footer area
footer_title_color: "#ffffff"
footer_text_color: "#77798f"
copy_right_year: "2020"
version: "v0.1"

# social media
rss_url: "/assets/feed.xml" #update the feed content in feed.xml file
facebook_url: "https://www.facebook.com/{company}" #link to your facebook account
twitter_url: "https://twitter.com/{company}" #link to your twitter account
github_url: "https://github.com/{company}" #link to your github account
linkedin_url: "https://www.linkedin.com/{company}" #link to your linkedin account
youtube_url: "https://www.youtube.com/{company}" #link to your youtube account

# sitemap
link_tools: #to show tools list in homepage footer section.
  - title: "Overview"
    url: "https://www.google.com/"
  - title: "Overview l2"
    url: "https://www.google.com/"
link_services: #to show service list in homepage footer section.
  - title: "Service"
    url: "https://www.google.com/"
  - title: "Service l2"
    url: "https://www.google.com/"
resources_limit: 3 #to limit number of resources that will be display in homepage footer section.
link_company: #to show company list in homepage footer section.
  - title: "Company"
    url: "https://www.google.com/"
  - title: "Company l2"
    url: "https://www.google.com/"

# Contact Us
action_url: "https://formspree.io/xknqrlvg"
redirect_url: "http://127.0.0.1:4000/contactus/"

#snippet of a posts’s content
excerpt_separator: <!--more-->

# Build settings
# theme: standardhub-theme
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  # - jekyll-paginate-category

# Pagination Settings
pagination:
  enabled: true
  per_page: 6
  permalink: "/page/:num/"
  title: " - page :num"
  limit: 0
  sort_field: "date"
  sort_reverse: true# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
